version: 0.2

env:
  variables:
    DIST_DIR: dist
    CLOUDFRONT_DISTRIBUTION_ID: YOUR_CLOUDFRONT_ID_HERE

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - yarn install
  build:
    commands:
      - echo Building the frontend...
      - yarn run build
  post_build:
    commands:
      - echo Deploying to S3 bucket $S3_BUCKET...
      - aws s3 sync $DIST_DIR s3://$S3_BUCKET --delete
      - echo Invalidating CloudFront cache...
      - >
        aws cloudfront create-invalidation
        --distribution-id $CLOUDFRONT_DISTRIBUTION_ID
        --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: $DIST_DIR
